name: Deploy Nginx Server

on:
  push:
    branches:
      - ansible_action

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ${{ secrets.PUBLIC_IP }}, ansible_action/ansible/create_nginx_server.yaml -u ec2-user --private-key $SSH_PRIVATE_KEY
