name: Deploy Nginx Server

on:
  push:
    branches:
      - ansible_action

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Output SSH key to file
      run: |
        mkdir ~/.ssh
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Configure ansible hosts
      run: |
        sudo mkdir /etc/ansible
        sudo touch /etc/ansible/hosts
        sudo echo ${{ secrets.PUBLIC_IP }} >> /etc/ansible/hosts
        ansible all -m ping -u ec2-user --private-key ~/.ssh/id_rsa

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ${{ secrets.PUBLIC_IP }}, ansible_action/ansible/create_nginx_server.yaml -u ec2-user --private-key ~/.ssh/id_rsa
