name: Deploy Nginx Server

on:
  push:
    branches:
      - ansible_action

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: Output SSH key to file
      run: |
        mkdir ~/.ssh
        echo "${{env.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Configure ansible hosts
      run: |
        mkdir ~/ansible
        touch ~/ansible/hosts
        echo ${{ env.PUBLIC_IP }} >> ~/ansible/hosts
        ansible all -i ${{ env.PUBLIC_IP }} -m ping -u ec2-user --private-key ~/.ssh/id_ed25519

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i ~/ansible/hosts, ansible_action/ansible/create_nginx_server.yaml -u ec2-user --private-key ~/.ssh/id_ed25519
